# General

[arch]
name = "Arch Linux"
description = "My daily driver, btw"

[linux]
name = "Linux"
description = ""

[i3]
name = "i3"
description = """I̶'̶l̶l̶ ̶s̶w̶i̶t̶c̶h̶ ̶t̶o̶ ̶S̶w̶a̶y̶.̶ ̶S̶o̶m̶e̶ ̶d̶a̶y̶.̶ ̶E̶v̶e̶n̶t̶u̶a̶l̶l̶y̶.̶ ̶B̶e̶f̶o̶r̶e̶ ̶v̶e̶r̶y̶ ̶l̶o̶n̶g̶.̶ ̶S̶o̶o̶n̶e̶r̶ ̶o̶r̶ ̶l̶a̶t̶e̶r̶.̶ ̶I̶n̶ ̶t̶i̶m̶e̶ ̶t̶o̶ ̶c̶o̶m̶e̶.̶ ̶C̶e̶r̶t̶a̶i̶n̶l̶y̶.̶.̶.̶
I actually did switch. Buuuuut, I'm to lazy to change the icon."""

[alacritty]
name = "Alacritty"
description = ""


# Programming languages

[rust]
name = "Rust"
description = """💖🦀
Befriended the borrow checker. Not the lifetimes though.
Click to see things I wrote in Rust."""
link = "https://github.com/mrsobakin?tab=repositories&q=&type=&language=rust"
themed_icons = true

[cpp]
name = "C++"
description = ""
link = "https://github.com/mrsobakin?tab=repositories&q=&type=&language=c%2B%2B"

[python]
name = "Python"
description = """This is probably the language I wrote most code in. It is slow as hell, is full of runtime exceptions, but it's simple and gets the job done. This readme was generated using Python!
Click to see things I wrote in it."""
link = "https://github.com/mrsobakin?tab=repositories&q=&type=&language=python"

[go]
name = "Go"
description = """I love Go, but I think that I'm cursed. Every time, and I mean *EVERY* time that I decide to write something in Go, I have to reimplement basic things. I had to write my own MPMC channel once.
Click to see things I wrote in Go."""
link = "https://github.com/mrsobakin?tab=repositories&q=&type=&language=go"

[javascript]
name = "Javascript"
description = "Javascript is so awful that its shittiness rolls over and it becomes good again."
link = "https://github.com/mrsobakin?tab=repositories&q=&type=&language=javascript"

[java]
name = "Java"
description = "For better or for worse, Java was *the* language I learned to code in. But now I hate it. Well, just as any other sane person."
link = "https://github.com/mrsobakin?tab=repositories&q=&type=&language=java"


# Databases

[sqlite]
name = "SQLite"
description = ""


# Devtools

[bash]
name = "Bash"
description = """I would like to say that I know bash, but I think that no one really does fully know it. I can write complex scripts, but I can never be sure that they won't break on some edge case.
Click to go to repository with my useful scripts"""
link = "https://github.com/mrsobakin/scripts"
themed_icons = true

[lua]
name = "Lua"
description = ""

[docker]
name = "Docker"
description = ""

[git]
name = "Git"
description = "I know my `git push --force` and manual hunk editing around it. Though I'm nowhere near being a git master."

# [github]
# name = "GitHub"
# description = ""
# themed_icons = true

[nvim]
name = "NeoVim"
description = """Don't know what to say about it. I write text in NeoVim. I even wrote a plugin for it in it.
Click to check out my NeoVim config (it will never be finished)"""
link = "https://github.com/mrsobakin/nvim-config/"

[md]
name = "Markdown"
description = """You'll be the judge of my markdown skills."""
# Click to see a write-up of hacks used in this README."""
themed_icons = true

[regex]
name = "Regex"
description = """My most favorite out of my most hated things thing. Regex is ugly and unreadable, slow, and always causes disasters. But ad-hoc, it's irreplaceable. Truly chaotic neutral.
It's also fun to mess around with."""
# Click to see my regex for divisibility by 13
themed_icons = true


# Everyday tools

[ffmpeg]
name = "FFmpeg"
description = "I still can't remember how to resize a video"

[wine]
name = "Wine"
description = """Except that I obviously use it, I am more or less familiar with its internals and the codebase. I tried to compile WineLib dlls with Rust, however I faced a problem known as a skill issue (I'm just too stupid for it). WineLib itself is too obscure and undocumented, let alone a its usage with Rust. Better luck next time.
(If you are familiar with WineLib and Rust and somehow reading this, please DM me. I would really appreciate your help!)"""
themed_icons = true

# [gimp]
# name = "GIMP"
# description = "Better than photoshop. Change my mind."


# Libraries, frameworks

# [tokio]
# name = "Tokio"
# description = ""
# themed_icons = true
#
# [react]
# name = "React"
# description = ""
#
# [fastapi]
# name = "FastAPI"
# description = ""
#
# [flask]
# name = "Flask"
# description = ""
# themed_icons = true


# Reverse engineering

# [qemu]
# name = "Qemu"
# description = ""

[wireshark]
name = "Wireshark"
description = ""
themed_icons = true

[mitmproxy]
name = "mitmproxy"
description = "An important tool in my reverse engineering toolkit. Numerous bugs have been found and numerous services have been reverse engineered with it."
themed_icons = true


# Games :)

[minecraft]
name = "Minecraft"
description = "Surprising to see a game in a tech stack, right? But there's a good reason why it's here - Minecraft was the main reason that brought me into computer science. It teached me the art of kludging, and I even decided to learn to code just so I could make mods for it. Needless to say that I still didn't made a single one :)"

[spigot]
name = "Spigot"
description = "Back in the day, this was what cool kids used to run Minecraft servers. I never did run my own server back then, but I did wrote a ton of plugins for the Spigot. It's the place where I got my unfortunate knowledge of Java."
